services:
  scala:
    image: jorgemartinezpizarro/lucas-lehmer-scala-server:latest
    restart: always
    ports:
      - 8080:8080

  go:
    image: jorgemartinezpizarro/lucas-lehmer-go-server:latest
    restart: always
    ports:
      - 5002:8080
